name: ansible-test
on:
  push:
  pull_request:
  schedule:
    - cron: 48 16 * * *

env:
  COLL_NS: flowerysong
  COLL_NAME: melange
  ANSIBLE_COLLECTIONS_PATHS: ${{ github.workspace }}

jobs:
  build_collection:
    name: build collection
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'git+https://github.com/ansible/ansible@stable-2.16#egg=ansible-core'

      - name: Build collection
        run: ansible-galaxy collection build -vv

      - name: Upload collection
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.COLL_NS }}-${{ env.COLL_NAME }}-*.tar.gz
          name: ${{ env.COLL_NS }}-${{ env.COLL_NAME }}

  static_analysis:
    needs: build_collection
    name: static analysis (${{ matrix.ansible_version.name }})
    strategy:
      matrix:
        ansible_version:
          - name: stable-2.15
            version: git+https://github.com/ansible/ansible@stable-2.15#egg=ansible-core
            python: 3.9
          - name: stable-2.16
            version: git+https://github.com/ansible/ansible@stable-2.16#egg=ansible-core
            python: 3.12
          - name: devel
            version: git+https://github.com/ansible/ansible#egg=ansible-core
            python: 3.12
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.ansible_version.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install '${{ matrix.ansible_version.version }}' pycodestyle pylint pyyaml voluptuous yamllint junit-xml

      - name: Download collection
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.COLL_NS }}-${{ env.COLL_NAME }}

      - name: Install collection
        run: ansible-galaxy collection install ${{ env.COLL_NS }}-${{ env.COLL_NAME }}-*.tar.gz

      - name: Run tests
        run: ansible-test sanity -v --color --docker
        working-directory: ./ansible_collections/${{ env.COLL_NS }}/${{ env.COLL_NAME }}
